.travis.yml
README.md
cmd/brew-formula-analytics.rb

Provide a `--json` option to provide JSON output of the data.

Add JSON output.

---

cmd/brew-formula-analytics.rb

- Don't output e.g. `wgetpaste` if you specify `wget` as the formula
- Comma separate counts
- Use tabular output for plain text
- Output totals

Improve output formatting

---

cmd/brew-formula-analytics.rb

Some more tricks to setup the RubyGems require path properly that will hopefully survive Ruby version changes.
CC @jcount @alyssais @ilovezfs can you see if this works for you? Thanks!
Fixes #4.

Fix Bundler setup

---

cmd/brew-formula-analytics.rb

brew-formula-analytics: handle maximum days ago.

---

README.md
cmd/brew-formula-analytics.rb

README: use short docs.brew.sh links.

---

cmd/brew-formula-analytics.rb

Allow the specification of multiple formulae on the command-line. This uses the batched report API so should be faster for up to 5 formulae.

formula-analytics: allow specifying multiple formulae.

---

cmd/brew-formula-analytics.rb

- Output 10,000 rather than 1,000 formulae
- Use both batching methods for increased performance
- Remove erroneous `formula` in JSON output

formulae-analytics: output format tweaks.

---

cmd/brew-formula-analytics.rb

This will be used by formulae.brew.sh to build groups of all core formulae for displaying their analytics on the formulae.brew.sh formulae pages.

formula-analytics: add --all-core-formulae-json option.

---

cmd/brew-formula-analytics.rb

brew-formula-analytics: output 10.14.

---

cmd/brew-formula-analytics.rb

Once https://github.com/Homebrew/brew/pull/5105 has been merged and `brew info -v` supports all the necessary features we can remove a bunch of the code here and make `brew formula-analytics` purely used to get data from Google Analytics and add it to https://formulae.brew.sh where it can be consumed by `brew info -v` and other tools.

brew-formula-analytics: only support full JSON output.

---

cmd/brew-formula-analytics.rb

Blocking https://github.com/Homebrew/homebrew-formula-analytics/pull/45

brew-formula-analytics: fix brew style.

---

cmd/brew-formula-analytics.rb

per https://github.com/Homebrew/formulae.brew.sh/issues/13

make cask install analytics available for output

---

cmd/brew-formula-analytics.rb

brew-formula-analytics: brew style --fix.

---

cmd/brew-formula-analytics.rb

Now we have an official name let's make our output nicer.

brew-formula-analytics: output macOS Catalina.

---

cmd/brew-formula-analytics.rb

brew-formula-analytics: remove unnecessary `to_f`.

---

cmd/brew-formula-analytics.rb

A little more explicit but perhaps more readable.

brew-formula-analytic: fix brew style.

---

.github/workflows/tests.yml

This should get CI green again.

workflows/tests: fix for built-in Linuxbrew.

---

cmd/formula-analytics.rb

Fix brew style

---

cmd/formula-analytics.rb

For https://github.com/Homebrew/brew/pull/10645

cmd/formula-analytics: fix brew style.

---

cmd/formula-analytics.rb

- describe 12.x as Monterey
- consolidate all 10.16/11.x and 12.x (and above) by major version

Cleanup macOS versions

---

cmd/formula-analytics.rb

For https://github.com/Homebrew/brew/pull/13433

cmd/formula-analytics: use `Dir.home` over `ENV["HOME"]`

---

cmd/formula-analytics.rb

For e.g. https://formulae.brew.sh/analytics/os-version/30d/

cmd/formula-analytics: add macOS Ventura.

---

cmd/formula-analytics.rb

Others are not implemented (yet).

cmd/formula-analytics: get formula install events from InfluxDB.

---

cmd/formula-analytics.rb

- dedupe macOS and Ubuntu versions
- use correct keys for OS versions and casks
- correctly generate `all_core_formulae_json`
- format counts correctly

formula-analytics: cleanup InfluxDB output

---

cmd/formula-analytics.rb

Will display more nicely on formulae.brew.sh.

cmd/formula-analytics: add macOS Sonoma.

---

cmd/formula-analytics.rb

- Add switches for the additional data types
- Add a constant for the earliest (full) InfluxDB data
- Rename Google Analytics constant accordingly
- Use new analytics_counts bucket for new, backfilled data
- Consolidate dimension_key assignment

formula-analytics: InfluxDB tweaks.

---

cmd/generate-analytics-api.rb

macOS and Linux analytics are now combined.

cmd/generate-analytics-api: no OS analytics.

---

Gemfile
cmd/formula-analytics.rb
cmd/generate-analytics-api.rb

- Reword and remove flags based on no more Google Analytics
- Remove all Google Analytics specific code
- Generate extra InfluxDB analytics categories
- Remove Google Analytics gem

Remove Google Analytics, generate extra categories

---

.github/workflows/tests.yml
cmd/generate-analytics-api.rb

Try to generate analytics fully on PRs from non-forks.

Improve analytics generation testing

---

cmd/formula-analytics.rb

Fix the output again to be the format that formulae.brew.sh expects.

cmd/formula-analytics: fix data output.

---

cmd/formula-analytics.rb

- Use a case statement instead of if/elsif/else.
- Cleanup more Linux distributions.

cmd/formula-analytics: cleanup code and Linux versions.

---

Gemfile.lock

We never removed the Google Analytics stuff from here.

Gemfile.lock: update.

---

cmd/formula-analytics.rb

Should resolve the issue in https://github.com/orgs/Homebrew/discussions/4675

fix: use different value from values array and check for nil

---

cmd/formula-analytics.rb

Fixes failing build on build-errors

fix: use any influx returned count

---

cmd/formula-analytics.rb

This makes formulae.brew.sh output a bit nicer.

cmd/formula-analytics: order core formulae by count.

---

cmd/formula-analytics.rb
cmd/formula-analytics.rbi
cmd/generate-analytics-api.rb
lib/pycall-setup.rbi

- Part of https://github.com/Homebrew/brew/issues/17297.

Bump files to Sorbet `typed: strict`
