.travis.yml
cmd/brew-formula-analytics.rb

Using the new rules in Homebrew/brew#2679 and check them on new PRs.

Fix RuboCop warnings.

---

cmd/brew-formula-analytics.rb

Lookup formulae names from the currently tapped taps to save a little bit of typing.
CC @ilovezfs who requested this.

brew-formula-analytics: use formulary lookup.

---

README.md
cmd/brew-formula-analytics.rb

Allow multiple categories to be specified at once and add a new `--os-version` argument to query based on OS version rather than formula.
Also, while we're here update an HTTP link to HTTPS and cleanup an outdated RuboCop rule, too.

Allow more categories to be specified

---

cmd/brew-formula-analytics.rb

In that case we want to ensure that we still search for something so provide a single `nil` in the formulae array so the formulae loop runs at least once but without a formula conditional.
Fixes #14

formula-analytics: handle no formula arguments.

---

cmd/brew-formula-analytics.rb

It's not reasonable to want to query analytics from users but not provide analytics yourself.

brew-formula-analytics: refuse to run with HOMEBREW_NO_ANALYTICS set.

---

README.md

Point out that this is now not needed for maintainers or end-users.

README: update analytics docs.

---

cmd/brew-formula-analytics.rb

Otherwise `formula` is used.
Missed from #59. CC @brianmorton FYI

formula-analytics: use cask key.

---

cmd/brew-formula-analytics.rb

As Homebrew doesn't do this implicitly any more for us.

brew-formula-analytics: require RubyGems explicitly.

---

cmd/brew-formula-analytics.rb

- Previously, the `ANALYTICS_VIEW_ID` was hardcoded to point to the
Homebrew one (120682403).
- Homebrew on Linux has its own Google Analytics account, with its own
view ID.
- I did consider a one-liner:
`ANALYTICS_VIEW_ID = ARGV.include?("--linux") ? "12345" : "67890".freeze`
but it seemed easier to read with the full `if` syntax.
- I also considered using `OS.mac?` and `OS.linux?`, but that would have
been messy if people on either of those OSes wanted to access the
others' GA data.

Set a `--linux` flag to use the 'Linuxbrew' analytics account

---

cmd/formula-analytics.rb

Note that I do not get a single result for 11.0 or for any system other than "Intel" for that matter.
I suspect Google Analytics might not yet support such user-agents yet. Either that or Apple have done a flawless job at hiding everything and have been using `HOMEBREW_NO_ANALYTICS` on all Apple Silicon machines - I guess we'll see when people start receiving dev kits.

cmd/formula-analytics: display Big Sur; relax major version regex

---

cmd/formula-analytics.rb

This is simpler and `Homebrew.install_gem_setup_path!` is going away.

formula-analytics: use Homebrew.install_bundler!.

---

cmd/formula-analytics.rb

As per Homebrew/brew#9225, consider any macOS version number starting with 11 to be Big Sur.
One question: do we also want to collapse all 11.x versions into a single entry, or keep them separate as they currently appear at https://formulae.brew.sh/analytics/os-version/30d/?

Adjust macOS version logic

---

cmd/formula-analytics.rb

Otherwise there's multiple `macOS Big Sur (11)` entries on https://formulae.brew.sh/analytics/os-version/30d/

cmd/formula-analytics: fix Big Sur version.

---

cmd/formula-analytics.rb

- fix `max_named` deprecation
- print JSON output by default without warning or needing flag

cmd/formula-analytics: tweak args handling.

---

Gemfile
Gemfile.lock

This is the new/currently updated one.

Gemfile*: use google-apis-analyticsreporting_v4 gem.

---

Gemfile.lock

0.1.1 has been yanked, breaking the formulae.brew.sh build.
Reverts Homebrew/homebrew-formula-analytics#220

Revert "build(deps): bump declarative-option from 0.1.0 to 0.1.1"

---

cmd/formula-analytics.rb

The counts of macOS >= 11 were all incorrect.

cmd/formula-analytics: fix incorrect OS version counting

---

Gemfile
Gemfile.lock
cmd/formula-analytics.rb

Adds a hidden `--influx` argument to read the analytics from InfluxDB rather than Google Analytics.
Merging this as-is so future PRs can focus on building out the data and we can ensure we don't get regressions here.

Start work on reading analytics from InfluxDB

---

cmd/generate-analytics-api.rb

This PR creates a `generate-analytics-api` command to generate the analytics API files needed for formulae.brew.sh. The command has no options and generates all of the macOS and Linux analytics in one go. There's now no way to generate one without the other since I couldn't think of a decent reason why we'd need to do that now, but if we want to retain that functionality it will be easy to do so.
I've compared the results of running this command and running `rake all_analytics` in `formulae.brew.sh`, and the results are the same.
See https://github.com/Homebrew/brew/issues/14730
`formulae.brew.sh` PR: https://github.com/Homebrew/formulae.brew.sh/pull/786

Add `generate-analytics-api` command

---

cmd/formula-analytics.rb

Fixes https://github.com/Homebrew/formulae.brew.sh/actions/runs/5193660963/jobs/9364484761#step:6:87

cmd/formula-analytics: fix default InfluxDB encoding

---

cmd/formula-analytics.rb

Updates to Gemfile.lock currently don't take place unless you delete `vendor` yourself.
This PR makes the code smarter by running a `bundle check` to see if an install is needed. This doesn't matter for CI, but did for me locally when I ran this command for the first time in months.
Requires https://github.com/Homebrew/brew/pull/15532 for `Homebrew.install_bundler!` not to be a slowdown.

cmd/formula-analytics: invoke bundle install if local install is stale

---

.rubocop.yml
cmd/formula-analytics.rb

We know which versions are always LTS to consolidate them.
While we're here, add a stub `.rubocop.yml` to make `rubocop` do the right thing.

formula-analytics: more Ubuntu version cleanup.

---

cmd/formula-analytics.rb
cmd/generate-analytics-api.rb

- skip tap formulae when generating homebrew/core JSON
- always use InfluxDB when generating analytics data

cmd: more InfluxDB changes.

---

cmd/formula-analytics.rb

Should fix the failing analytics

fix: allow core-formulae on cask metrics

---

cmd/formula-analytics.rb

Need to ensure we handle actual integers and only use the base parameter for strings.

cmd/formula-analytics: better handle various types of counts.

---

cmd/formula-analytics.rb

- Fixing tap syntax CI failures surfaced in https://github.com/Homebrew/brew/pull/16346.

Freeze `VENDOR_RUBY` constant to appease RuboCop

---

cmd/formula-analytics.rb

- homebrew/core only includes `--HEAD` options but our analytics data includes others (so strip them out)
- the formula name should only be the actual name, not the name and the options, to be in the format formulae.brew.sh expects

cmd/formula-analytics: fix --all-core-formulae-json

---

cmd/generate-analytics-api.rb

`system_command` has been removed from the global scope in https://github.com/Homebrew/brew/pull/16540 so let's switch to use public API instead.

cmd/generate-analytics-api: avoid system_command

---

cmd/formula-analytics.rb
cmd/generate-analytics-api.rb

For https://github.com/Homebrew/brew/pull/16848

Use RuboCop default hash syntax.

---

cmd/generate-analytics-api.rb

Just a quick fix for https://github.com/Homebrew/formulae.brew.sh/issues/1104
Not sure how to reproduce original `result.merged_output` behavior. By default `Utils.popen_read` sends stderr to `/dev/null`. 
Did try a `StringIO` but wasn't successful, e.g.
```rb
stderr = StringIO.new
result = Utils.popen_read(..., err: stderr)
```
I was able to get some stderr via `IO.pipe` but not sure if best way, e.g.
```rb
stderr = ""
IO.pipe do |rd, wr|
result = Utils.popen_read(..., err: wr)
wr.close
stderr = rd.read
end
```

cmd/generate-analytics-api: remove merged_output

---

cmd/formula-analytics.rb

cmd/formula-analytics: skip dimensions with invalid characters.

---

cmd/formula-analytics.rb
cmd/generate-analytics-api.rb

These new categories are available from https://github.com/Homebrew/brew/pull/16847
There's a few TODO here that I'd love help with but don't need to block getting this data flowing.

Add command, command options and test bot data

---

cmd/generate-analytics-api.rb

These aren't generating valid data yet so let's avoid attempting any generation for now.

cmd/generate-analytics-api: remove command-run-options, test-bot-test.

---

cmd/formula-analytics.rb

This means there are too few events to be useful and skipping them avoids bloating our analytics pages with irrelevant data.

formula-analytics: skip zero count items.

---

cmd/generate-analytics-api.rb

Found another vestige of the Linuxbrew era.

generate-analytics-api: skip generating analytics-linux directories

---

Gemfile
cmd/formula-analytics.rb

Fixes https://github.com/Homebrew/formulae.brew.sh/issues/1212

Allow Portable Ruby to mismatch .ruby-version

---

cmd/formula-analytics.rb

While fixing `brew style` tap support (https://github.com/Homebrew/brew/pull/17482), brew CI surfaced some style issues in this tap. This fixes the issues, so brew CI will pass and the fix can be merged.

Fix style issues

---

cmd/formula-analytics.rb

It was mapping `KDE neon 6.0` to `KDE neon 0` which doesn't make sense. Make the regex non-greedy.

cmd/formula-analytics: fix KDE neon handling

---

cmd/generate-analytics-api.rb

See also: https://github.com/Homebrew/homebrew-core/pull/176608

cmd/generate-analytics-api: fix `cmd_args` usage

---

cmd/formula-analytics.rb
cmd/generate-analytics-api.rb

Output `brew-command-run-options` and `brew-test-bot-test` analytics now that they are working.
While we're here:
- improve the unauthenticated error message to be more helpful.
- remove `--with*` options from the command output
- remove TODO comments for cleanup of bad data that can't been done.

cmd/generate-analytics-api: generate more analytics.

---

cmd/formula-analytics.rb

cmd/formula-analytics: filter bad env data

---

lib/pycall-setup.rb
lib/pycall-setup.rbi

- Part of https://github.com/Homebrew/brew/issues/17297.
- ❌ TODO: More 🍨. This is just the bare minimum so far to make `brew tc homebrew/formula-analytics` come back green. And all the fixing the actual code because apparently Sorbet causes it all to break. 😅

Enable Sorbet typechecking

---

cmd/formula-analytics.rb

```
Error: Parameter 'dimension': Expected type String, got type NilClass
Caller: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics/cmd/formula-analytics.rb:248
Definition: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics/cmd/formula-analytics.rb:375
```

The `dimension` param can be blank

---

lib/pycall-setup.rb

I'm adding a new RuboCop in https://github.com/Homebrew/brew/pull/18842 and CI for that is failing because this line doesn't conform to the cop.
By adding a comment explaining why the cop was disable, the linter is appeased. I cribbed the comment from https://github.com/Homebrew/homebrew-formula-analytics/commit/9780d547f01c24339e4bd1b998dea372c321d1d3

Add a comment for rubocop disable comment

---

cmd/formula-analytics.rb

This PR removes old versions of Mac OS X and OS X that Homebrew no longer runs on. None of these versions have any data in our analytics. This also normalizes Amazon Linux 2023 + future year versions so we're not reporting every release individually.

cmd/formula-analytics: update OS versions
